name: business_os
description: "An intelligent Business Operating System for managing, understanding, and growing businesses."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^3.0.0
  get_it: ^9.3.0
  go_router: ^17.5.0
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0
  google_sign_in: ^7.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.3.2
  printing: ^5.14.3
  pdf: ^3.12.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/Logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#DDF7FF"
  adaptive_icon_foreground: "assets/logos/Logo.png"
  remove_alpha_ios: true

  android_legacy: true
  android_adaptive_icon_background: "#DDF7FF"
