// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTNocNRc7QIs4RSHjqWz1TVzXJfQNIAo',
    appId: '1:223428772506:web:3a1f2acb09e1273bc79523',
    messagingSenderId: '223428772506',
    projectId: 'business-os-958a2',
    authDomain: 'business-os-958a2.firebaseapp.com',
    storageBucket: 'business-os-958a2.firebasestorage.app',
    measurementId: 'G-MB61T15KVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXNWMO8VXP8Hncw4GMxv6cJRHgEFP_C0',
    appId: '1:223428772506:android:0b619f8cc0ca04b7c79523',
    messagingSenderId: '223428772506',
    projectId: 'business-os-958a2',
    storageBucket: 'business-os-958a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7vtFas1knwBLlVel8ah58VuOVYqi8rg',
    appId: '1:223428772506:ios:eac78ee20ce57c7bc79523',
    messagingSenderId: '223428772506',
    projectId: 'business-os-958a2',
    storageBucket: 'business-os-958a2.firebasestorage.app',
    iosBundleId: 'com.example.businessOs',
  );
}
